site_name: Zimu Xia
site_url: https://zzzzxia.github.io/zxia/

theme:
  name: material

  palette:

    - scheme: default
      primary: indigo    
      accent: cyan           
      toggle:
        icon: material/weather-night
        name: switch to dark mode
 
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: switch to light mode


  font:
    text: Noto Serif         
    code: Roboto Mono         


  features:
    - navigation.instant      
    - navigation.tracking     
    - navigation.tabs         
    - navigation.top          
    - search.suggest         
    - search.highlight        


nav:
  - Home: index.md
  - Map v1: map/index.md
  - Paper Notes:
    - Review: notes/review.md
    - Empirical: notes/empirical.md
